/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern GoSlice EncodeBase8192(GoSlice inp);
extern GoSlice DecodeBase8192(GoSlice inp);
extern GoSlice EncodeBase4096(GoSlice inp);
extern GoSlice DecodeBase4096(GoSlice inp);
extern GoSlice EncodeBase512(GoSlice inp);
extern GoSlice DecodeBase512(GoSlice inp);
extern GoSlice EncodeBase256(GoSlice inp);
extern GoSlice DecodeBase256(GoSlice inp);
extern GoSlice EncodeBaseMath(GoSlice inp);
extern GoSlice DecodeBaseMath(GoSlice inp);
extern GoSlice EncodeBaseTanWi(GoSlice inp);
extern GoSlice DecodeBaseTanWi(GoSlice inp);
extern GoSlice EncodeBase128(GoSlice inp);
extern GoSlice DecodeBase128(GoSlice inp);
extern GoSlice EncodeBaseDevanagari(GoSlice inp);
extern GoSlice DecodeBaseDevanagari(GoSlice inp);
extern GoSlice EncodeBase64(GoSlice inp);
extern GoSlice DecodeBase64(GoSlice inp);
extern GoSlice EncodeBase64Gua(GoSlice inp);
extern GoSlice DecodeBase64Gua(GoSlice inp);
extern GoSlice EncodeBaseRune(GoSlice inp);
extern GoSlice DecodeBaseRune(GoSlice inp);
extern GoSlice EncodeBaseMongolian(GoSlice inp);
extern GoSlice DecodeBaseMongolian(GoSlice inp);
extern GoSlice EncodeBaseBox(GoSlice inp);
extern GoSlice DecodeBaseBox(GoSlice inp);
extern GoSlice EncodeBase32(GoSlice inp);
extern GoSlice DecodeBase32(GoSlice inp);
extern GoSlice EncodeBaseTibetan(GoSlice inp);
extern GoSlice DecodeBaseTibetan(GoSlice inp);
extern GoSlice EncodeBase16(GoSlice inp);
extern GoSlice DecodeBase16(GoSlice inp);
extern GoSlice EncodeBaseBuginese(GoSlice inp);
extern GoSlice DecodeBaseBuginese(GoSlice inp);
extern GoSlice EncodeBase8Gua(GoSlice inp);
extern GoSlice DecodeBase8Gua(GoSlice inp);

#ifdef __cplusplus
}
#endif
